# <font color=green> PYTHON PARA DATA SCIENCE - PANDAS
---

# <font color=green> 1. INTRODUÇÃO AO PYTHON
---

# 1.1 Introdução

> Python é uma linguagem de programação de alto nível com suporte a múltiplos paradigmas de programação. É um projeto *open source* e desde seu surgimento, em 1991, vem se tornando uma das linguagens de programação interpretadas mais populares. 
>
> Nos últimos anos Python desenvolveu uma comunidade ativa de processamento científico e análise de dados e vem se destacando como uma das linguagens mais relevantes quando o assundo é ciência de dados e machine learning, tanto no ambiente acadêmico como também no mercado.

# 1.2 Instalação e ambiente de desenvolvimento

### Instalação Local

### https://www.python.org/downloads/
### ou
### https://www.anaconda.com/distribution/

### Google Colaboratory

### https://colab.research.google.com

### Verificando versão

In [ ]:
!python -V

Python 3.7.12

# 1.3 Trabalhando com dados

In [8]:
import pandas as pd
pd.set_option('display.max_rows', 5) #SETA O MAXIMO DE LINHAS QUE APARECERÁ NO DATASET
# pd.set_option('display.max_columns', 5) #SETA O MAXIMO DE COLUNAS QUE APARECERÁ NO DATASET

In [ ]:
dataset = pd.read_csv('db.csv', sep = ';')

In [ ]:
dataset

                 Nome  ...      Valor
0       Jetta Variant  ...   88078.64
1              Passat  ...  106161.94
..                ...  ...        ...
256  Aston Martin DB5  ...  122110.90
257             Macan  ...   90381.47

[258 rows x 7 columns]

In [ ]:
dataset.dtypes

Nome              object
Motor             object
Ano                int64
Quilometragem    float64
Zero_km             bool
Acessórios        object
Valor            float64
dtype: object

In [ ]:
dataset[['Quilometragem', 'Valor']].describe() #ESTATISTICAS DESCRITIVAS

       Quilometragem          Valor
count     197.000000     258.000000
mean    58278.421320   98960.513101
std     35836.733259   29811.932305
min       107.000000   50742.100000
25%     27505.000000   70743.512500
50%     55083.000000   97724.380000
75%     90495.000000  124633.302500
max    119945.000000  149489.920000

In [ ]:
dataset.info() #INFORMAÇÕES

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 258 entries, 0 to 257
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Nome           258 non-null    object
 1   Motor          258 non-null    object
 2   Ano            258 non-null    int64
 3   Quilometragem  197 non-null    float64
 4   Zero_km        258 non-null    bool
 5   Acessórios     258 non-null    object
 6   Valor          258 non-null    float64
dtypes: bool(1), float64(2), int64(1), object(3)
memory usage: 12.5+ KB

# <font color=green> 2. TRABALHANDO COM TUPLAS
---

# 2.1 Criando tuplas

Tuplas são sequências imutáveis que são utilizadas para armazenar coleções de itens, geralmente heterogêneos. Podem ser construídas de várias formas:
```
- Utilizando um par de parênteses: ( )
- Utilizando uma vírgula à direita: x,
- Utilizando um par de parênteses com itens separados por vírgulas: ( x, y, z )
- Utilizando: tuple() ou tuple(iterador)
```

In [ ]:
nomes_carros = tuple(['Jetta Variant', 'Passat', 'Crossfox', 'DS5'])
nomes_carros

('Jetta Variant', 'Passat', 'Crossfox', 'DS5')

In [ ]:
type(nomes_carros)

tuple

# 2.2 Seleções em tuplas

In [ ]:
nomes_carros[0]

'Jetta Variant'

In [ ]:
nomes_carros[1]

'Passat'

In [ ]:
nomes_carros[-1]

'DS5'

In [ ]:
nomes_carros = ('Jetta Variant', 'Passat', 'Crossfox', 'DS5', ('Fusca', 'Gol', 'C4'))
nomes_carros

# 2.3 Iterando em tuplas

In [ ]:
nomes_carros = ('Jetta Variant', 'Passat', 'Crossfox', 'DS5')
nomes_carros

In [ ]:
for item in nomes_carros:
  print(item)

Jetta Variant
Passat
Crossfox
DS5

### Desempacotamento de tuplas

In [ ]:
carro_1, carro_2, carro_3, carro_4 = nomes_carros

In [ ]:
carro_1

'Jetta Variant'

In [ ]:
carro_2

'Passat'

In [ ]:
_, C, *_ = nomes_carros

In [ ]:
C

'Passat'

## *zip()*

https://docs.python.org/3.6/library/functions.html#zip

In [ ]:
carros = ['Jetta Variant', 'Passat', 'Crossfox', 'DS5']
carros

['Jetta Variant', 'Passat', 'Crossfox', 'DS5']

In [ ]:
valores = [88078.64, 106161.94, 72832.16, 124549.07]
valores

[88078.64, 106161.94, 72832.16, 124549.07]

In [ ]:
list (zip (carros, valores)) #iterar com ZIP

[('Jetta Variant', 88078.64),
 ('Passat', 106161.94),
 ('Crossfox', 72832.16),
 ('DS5', 124549.07)]

In [ ]:
for item in zip(carros, valores):
  print(item)

In [ ]:
for carro, valor in zip(carros, valores):
  print(carro, valor)

Jetta Variant 88078.64
Passat 106161.94
Crossfox 72832.16
DS5 124549.07

In [ ]:
for carro, valor in zip(carros, valores):
  if(valor > 100000):
    print(carro)

Passat
DS5

# <font color=green> 3. TRABALHANDO COM DICIONÁRIOS
---

# 3.1 Criando dicionários

Listas são coleções sequenciais, isto é, os itens destas sequências estão ordenados e utilizam índices (números inteiros) para acessar os valores.

Os dicionários são coleções um pouco diferentes. São estruturas de dados que representam um tipo de mapeamento. Mapeamentos são coleções de associações entre pares de valores onde o primeiro elemento do par é conhecido como chave (*key*) e o segundo como valor (*value*).

```
dicionario = {key_1: value_1, key_2: value_2, ..., key_n: value_n}
```

https://docs.python.org/3.6/library/stdtypes.html#typesmapping

In [ ]:
carros = ['Jetta Variant', 'Passat', 'Crossfox']
carros

['Jetta Variant', 'Passat', 'Crossfox']

In [ ]:
valores = [88078.64, 106161.94, 72832.16]
valores

[88078.64, 106161.94, 72832.16]

In [ ]:
carros.index('Passat')

1

In [ ]:
valores[carros.index('Passat')]

106161.94

In [ ]:
dados = {'Jetta Variant': 88078.64, 'Passat': 106161.94, 'Crossfox': 72832.16}
dados

{'Crossfox': 72832.16, 'Jetta Variant': 88078.64, 'Passat': 106161.94}

In [ ]:
dados = dict(zip(carros, valores))
dados

{'Crossfox': 72832.16, 'Jetta Variant': 88078.64, 'Passat': 106161.94}

### Criando dicionários com *zip()*

# 3.2 Operações com dicionários

## *dict[ key ]*

Retorna o valor correspondente à chave (*key*) no dicionário.

In [ ]:
dados['Passat']

106161.94

## *key in dict*

Retorna **True** se a chave (*key*) for encontrada no dicionário.

In [ ]:
'Passat' in dados

True

In [ ]:
'Fusca' in dados

False

In [ ]:
'Fusca' not in dados

True

## *len(dict)*

Retorna o número de itens do dicionário.

In [ ]:
len(dados)

3

## *dict[ key ] = value*

Inclui um item ao dicionário.

In [ ]:
dados['DS5'] = 100000

In [ ]:
dados

{'Crossfox': 72832.16,
 'DS5': 100000,
 'Jetta Variant': 88078.64,
 'Passat': 106161.94}

## *del dict[ key ]*

Remove o item de chave (*key*) do dicionário.

In [ ]:
del dados['Passat']

In [ ]:
dados

{'Crossfox': 72832.16, 'DS5': 100000, 'Jetta Variant': 88078.64}

In [ ]:
dados = {
    'Passat': {
        'ano': 2012,
        'km': 50000,
        'valor': 75000,
        'acessorios': ['Airbag', 'ABS']
    }, 
    'Crossfox': {
        'ano': 2015,
        'km': 35000,
        'valor': 25000
    }
}

In [ ]:
'acessorios' in dados['Crossfox']

False

In [ ]:
'acessorios' in dados['Passat']

True

In [ ]:
dados['Crossfox']['valor']

25000

In [ ]:
dados['Passat']['acessorios']

['Airbag', 'ABS']

# 3.3 Métodos de dicionários

## *dict.update()*

Atualiza o dicionário.

In [ ]:
dados = {'Crossfox': 72832.16, 'DS5': 124549.07, 'Jetta Variant': 88078.64}
dados

{'Crossfox': 72832.16, 'DS5': 124549.07, 'Jetta Variant': 88078.64}

In [ ]:
dados.update({'Passat': 106161.94})
dados

{'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Jetta Variant': 88078.64,
 'Passat': 106161.94}

In [ ]:
dados.update({'Passat': 106161.95, 'Fusca': 150000}) #Atualiza valores e adiciona
dados

{'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Fusca': 150000,
 'Jetta Variant': 88078.64,
 'Passat': 106161.95}

## *dict.copy()*

Cria uma cópia do dicionário.

In [ ]:
dadosCopy = dados.copy()
dadosCopy

{'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Fusca': 150000,
 'Jetta Variant': 88078.64,
 'Passat': 106161.95}

In [ ]:
del dadosCopy['Fusca']
dadosCopy

{'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Jetta Variant': 88078.64,
 'Passat': 106161.95}

In [ ]:
dadosCopy.pop('Passat')

106161.95

In [ ]:
dadosCopy

{'Crossfox': 72832.16, 'DS5': 124549.07, 'Jetta Variant': 88078.64}

## *dict.pop(key[, default ])*

Se a chave for encontrada no dicionário, o item é removido e seu valor é retornado. Caso contrário, o valor especificado como *default* é retornado. Se o valor *default* não for fornecido e a chave não for encontrada no dicionário um erro será gerado.

In [ ]:
dadosCopy.pop('Passat')

KeyError: ignored

In [ ]:
dadosCopy.pop('Passat', 'Chave não encontrada')

'Chave não encontrada'

## *dict.clear()*

Remove todos os itens do dicionário.

# 3.4 Iterando em dicionários

## *dict.keys()*

Retorna uma lista contendo as chaves (*keys*) do dicionário.

In [ ]:
dados.keys()

dict_keys(['Crossfox', 'DS5', 'Jetta Variant', 'Passat', 'Fusca'])

In [ ]:
for key in dados:
  print(dados[key])

72832.16
124549.07
88078.64
106161.95
150000

In [ ]:
for key in dados:
  print(key)

Crossfox
DS5
Jetta Variant
Passat
Fusca

## *dict.values()*

Retorna uma lista com todos os valores (*values*) do dicionário.

In [ ]:
dados.values()

dict_values([72832.16, 124549.07, 88078.64, 106161.95, 150000])

## *dict.items()*

Retorna uma lista contendo uma tupla para cada par chave-valor (*key-value*) do dicionário.

In [ ]:
dados.items()

dict_items([('Crossfox', 72832.16), ('DS5', 124549.07), ('Jetta Variant', 88078.64), ('Passat', 106161.95), ('Fusca', 150000)])

In [ ]:
for item in dados.items():
    print(item)

('Crossfox', 72832.16)
('DS5', 124549.07)
('Jetta Variant', 88078.64)
('Passat', 106161.95)
('Fusca', 150000)

In [ ]:
for key, value in dados.items():
    print(key, value)

Crossfox 72832.16
DS5 124549.07
Jetta Variant 88078.64
Passat 106161.95
Fusca 150000

In [ ]:
for key, value in dados.items():
  if (value > 100000):
    print(key)

DS5
Passat
Fusca

In [ ]:
dados = {
    'Crossfox': {'valor': 72000, 'ano': 2005}, 
    'DS5': {'valor': 125000, 'ano': 2015}, 
    'Fusca': {'valor': 150000, 'ano': 1976}, 
    'Jetta': {'valor': 88000, 'ano': 2010}, 
    'Passat': {'valor': 106000, 'ano': 1998}
}
dados

{'Crossfox': {'ano': 2005, 'valor': 72000},
 'DS5': {'ano': 2015, 'valor': 125000},
 'Fusca': {'ano': 1976, 'valor': 150000},
 'Jetta': {'ano': 2010, 'valor': 88000},
 'Passat': {'ano': 1998, 'valor': 106000}}

In [ ]:
for item in dados.items():
    if(item[1]['ano'] >= 2000):
        print(item[0])

Crossfox
DS5
Jetta

# <font color=green> 4. FUNÇÕES E PACOTES
---
    
Funções são unidades de código reutilizáveis que realizam uma tarefa específica, podem receber alguma entrada e também podem retornar alguma resultado.

# 4.1 Built-in function

A linguagem Python possui várias funções integradas que estão sempre acessíveis. Algumas já utilizamos em nosso treinamento: type(), print(), zip(), len(), set() etc.

https://docs.python.org/3.6/library/functions.html

In [ ]:
dados = {'Jetta Variant': 88078.64, 'Passat': 106161.94, 'Crossfox': 72832.16}
dados

{'Crossfox': 72832.16, 'Jetta Variant': 88078.64, 'Passat': 106161.94}

In [ ]:
valores = []

for valor in dados.values():
  valores.append(valor)
valores

[88078.64, 106161.94, 72832.16]

In [ ]:
sum(dados.values())

267072.74

# 4.2 Definindo funções sem e com parâmetros

### Funções sem parâmetros

#### Formato padrão

```
def <nome>():
    <instruções>
```

In [ ]:
def media(number_1, number_2, number_3):
  valor = (number_1 + number_2 +number_3) / 3
  print(valor)

In [ ]:
media(1,2,3)

2.0

### Funções com parâmetros

#### Formato padrão

```
def <nome>(<param_1>, <param_2>, ..., <param_n>):
    <instruções>
```

In [ ]:
def media(lista):
  valor = sum(lista) / len(lista)
  print(valor)

In [ ]:
resultado = media ([1, 2, 3, 4, 5, 6, 7, 8, 9])

5.0

In [ ]:
type(resultado)

NoneType

In [ ]:
resultado.dtype() #não retorna valor

AttributeError: ignored

# 4.3 Definindo funções que retornam valores

### Funções que retornam um valor

#### Formato padrão

```
def <nome>(<param_1>, <param_2>, ..., <param_n>):
    <instruções>
    return <resultado>
```

In [ ]:
def media(lista):
  valor = sum(lista) / len(lista)
  print(valor)

In [ ]:
def media(lista):
  valor = sum(lista) / len(lista)
  return (valor, len(lista))

In [ ]:
media([1, 2, 3, 4, 5, 6, 7, 8])

(4.5, 8)

In [ ]:
resultado = media([1, 2, 3, 4, 5, 6, 7, 8])
resultado #Agora retorna valor

(4.5, 8)

### Funções que retornam mais de um valor

#### Formato padrão

```
def <nome>(<param_1>, <param_2>, ..., <param_n>):
    <instruções>
    return (<resultado_1>, <resultado_2>, ..., <resultado_n>)
```

In [ ]:
resultado, n = media([1, 2, 3, 4, 5, 6, 7, 8, 9])
resultado

5.0

In [ ]:
n

9

In [ ]:
dados = {
    'Crossfox': {'km': 35000, 'ano': 2005}, 
    'DS5': {'km': 17000, 'ano': 2015}, 
    'Fusca': {'km': 130000, 'ano': 1979}, 
    'Jetta': {'km': 56000, 'ano': 2011}, 
    'Passat': {'km': 62000, 'ano': 1999}
}

In [ ]:
def km_media(dataset, ano_atual):
    result = {}
    for item in dataset.items():
        media = item[1]['km'] / (ano_atual - item[1]['ano'])
        result.update({ item[0]: media })
    return result

In [ ]:
km_media(dados, 2019)

{'Crossfox': 2500.0,
 'DS5': 4250.0,
 'Fusca': 3250.0,
 'Jetta': 7000.0,
 'Passat': 3100.0}

In [ ]:
dados = {
    'Crossfox': {'km': 35000, 'ano': 2005}, 
    'DS5': {'km': 17000, 'ano': 2015}, 
    'Fusca': {'km': 130000, 'ano': 1979}, 
    'Jetta': {'km': 56000, 'ano': 2011}, 
    'Passat': {'km': 62000, 'ano': 1999}
}

In [ ]:
def km_media(dataset, ano_atual):
    result = {}
    for item in dataset.items():
        media = item[1]['km'] / (ano_atual - item[1]['ano'])
        item[1].update({ 'km_media': media })
        result.update({ item[0]: item[1] })
    return result

In [ ]:
km_media(dados, 2019)

{'Crossfox': {'ano': 2005, 'km': 35000, 'km_media': 2500.0},
 'DS5': {'ano': 2015, 'km': 17000, 'km_media': 4250.0},
 'Fusca': {'ano': 1979, 'km': 130000, 'km_media': 3250.0},
 'Jetta': {'ano': 2011, 'km': 56000, 'km_media': 7000.0},
 'Passat': {'ano': 1999, 'km': 62000, 'km_media': 3100.0}}

# <font color=green> 5. PANDAS BÁSICO
---

**versão: 0.25.2**
  
Pandas é uma ferramenta de manipulação de dados de alto nível, construída com base no pacote Numpy. O pacote pandas possui estruturas de dados bastante interessantes para manipulação de dados e por isso é muito utilizado por cientistas de dados.


## Estruturas de Dados

### Series

Series são arrays unidimensionais rotulados capazes de armazenar qualquer tipo de dado. Os rótulos das linhas são chamados de **index**. A forma básica de criação de uma Series é a seguinte:


```
    s = pd.Series(dados, index = index)
```

O argumento *dados* pode ser um dicionário, uma lista, um array Numpy ou uma constante.

### DataFrames

DataFrame é uma estrutura de dados tabular bidimensional com rótulos nas linha e colunas. Como a Series, os DataFrames são capazes de armazenar qualquer tipo de dados.


```
    df = pd.DataFrame(dados, index = index, columns = columns)
```

O argumento *dados* pode ser um dicionário, uma lista, um array Numpy, uma Series e outro DataFrame.

**Documentação:** https://pandas.pydata.org/pandas-docs/version/0.25/

In [1]:
import pandas as pd

# 5.1 Estruturas de dados

### Criando uma Series a partir de uma lista

### Criando um DataFrame a partir de uma lista de dicionários

In [ ]:
dados = [
    {'Nome': 'Jetta Variant', 'Motor': 'Motor 4.0 Turbo', 'Ano': 2003, 'Quilometragem': 44410.0, 'Zero_km': False, 'Valor': 88078.64},
    {'Nome': 'Passat', 'Motor': 'Motor Diesel', 'Ano': 1991, 'Quilometragem': 5712.0, 'Zero_km': False, 'Valor': 106161.94},
    {'Nome': 'Crossfox', 'Motor': 'Motor Diesel V8', 'Ano': 1990, 'Quilometragem': 37123.0, 'Zero_km': False, 'Valor': 72832.16}
]

In [ ]:
dados

[{'Ano': 2003,
  'Motor': 'Motor 4.0 Turbo',
  'Nome': 'Jetta Variant',
  'Quilometragem': 44410.0,
  'Valor': 88078.64,
  'Zero_km': False},
 {'Ano': 1991,
  'Motor': 'Motor Diesel',
  'Nome': 'Passat',
  'Quilometragem': 5712.0,
  'Valor': 106161.94,
  'Zero_km': False},
 {'Ano': 1990,
  'Motor': 'Motor Diesel V8',
  'Nome': 'Crossfox',
  'Quilometragem': 37123.0,
  'Valor': 72832.16,
  'Zero_km': False}]

In [ ]:
dataset = pd.DataFrame(dados)

In [ ]:
dataset

            Nome            Motor   Ano  Quilometragem  Zero_km      Valor
0  Jetta Variant  Motor 4.0 Turbo  2003        44410.0    False   88078.64
1         Passat     Motor Diesel  1991         5712.0    False  106161.94
2       Crossfox  Motor Diesel V8  1990        37123.0    False   72832.16

In [ ]:
dataset[['Ano', 'Nome', 'Motor', 'Quilometragem', 'Zero_km', 'Valor']] #Ordenar estrutura

### Criando um DataFrame a partir de um dicionário

In [ ]:
dados = {
    'Nome': ['Jetta Variant', 'Passat', 'Crossfox'], 
    'Motor': ['Motor 4.0 Turbo', 'Motor Diesel', 'Motor Diesel V8'],
    'Ano': [2003, 1991, 1990],
    'Quilometragem': [44410.0, 5712.0, 37123.0],
    'Zero_km': [False, False, False],
    'Valor': [88078.64, 106161.94, 72832.16]
}

    Ano           Nome            Motor  Quilometragem  Zero_km      Valor
0  2003  Jetta Variant  Motor 4.0 Turbo        44410.0    False   88078.64
1  1991         Passat     Motor Diesel         5712.0    False  106161.94
2  1990       Crossfox  Motor Diesel V8        37123.0    False   72832.16

### Criando um DataFrame a partir de uma arquivo externo

In [2]:
dataset = pd.read_csv('db.csv', sep = ';', index_col = ['Nome'])

In [3]:
dataset

                                       Motor  ...      Valor
Nome                                          ...
Jetta Variant                Motor 4.0 Turbo  ...   88078.64
Passat                          Motor Diesel  ...  106161.94
Crossfox                     Motor Diesel V8  ...   72832.16
DS5                          Motor 2.4 Turbo  ...  124549.07
Aston Martin DB4             Motor 2.4 Turbo  ...   92612.10
...                                      ...  ...        ...
Phantom 2013                        Motor V8  ...   51759.58
Cadillac Ciel concept               Motor V8  ...   51667.06
Classe GLK             Motor 5.0 V8 Bi-Turbo  ...   68934.03
Aston Martin DB5                Motor Diesel  ...  122110.90
Macan                        Motor Diesel V6  ...   90381.47

[258 rows x 6 columns]

# 5.2 Seleções com DataFrames

### Selecionando colunas

In [ ]:
dataset['Valor']

0       88078.64
1      106161.94
2       72832.16
3      124549.07
4       92612.10
         ...
253     51759.58
254     51667.06
255     68934.03
256    122110.90
257     90381.47
Name: Valor, Length: 258, dtype: float64

In [ ]:
dataset[['Valor']]

         Valor
0     88078.64
1    106161.94
2     72832.16
3    124549.07
4     92612.10
..         ...
253   51759.58
254   51667.06
255   68934.03
256  122110.90
257   90381.47

[258 rows x 1 columns]

### Selecionando linhas - [ i : j ] 

<font color=red>**Observação:**</font> A indexação tem origem no zero e nos fatiamentos (*slices*) a linha com índice i é **incluída** e a linha com índice j **não é incluída** no resultado.

In [ ]:
dataset[0:3]

            Nome  ...      Valor
0  Jetta Variant  ...   88078.64
1         Passat  ...  106161.94
2       Crossfox  ...   72832.16

[3 rows x 7 columns]

### Utilizando .loc para seleções

<font color=red>**Observação:**</font> Seleciona um grupo de linhas e colunas segundo os rótulos ou uma matriz booleana.

In [ ]:
dataset.loc['Passat']

Motor                                                 Motor Diesel
Ano                                                           1991
Quilometragem                                                 5712
Zero_km                                                      False
Acessórios       ['Central multimídia', 'Teto panorâmico', 'Fre...
Valor                                                       106162
Name: Passat, dtype: object

In [ ]:
dataset.loc[['Passat', 'DS5']]

In [ ]:
dataset.loc[['Passat', 'DS5'], ['Motor', 'Valor']]

                  Motor      Valor
Nome
Passat     Motor Diesel  106161.94
DS5     Motor 2.4 Turbo  124549.07

### Utilizando .iloc para seleções

<font color=red>**Observação:**</font> Seleciona com base nos índices, ou seja, se baseia na posição das informações.

In [ ]:
dataset.iloc[1]

In [ ]:
dataset.iloc[[1]]

In [ ]:
dataset.iloc[1:4, [0, 5, 2]]

In [ ]:
dataset.iloc[[1, 42, 22], [0, 5, 2]]

In [ ]:
dataset.iloc[:, [0, 5, 2]]

# 5.3 Queries com DataFrames

In [5]:
select = dataset.Motor == 'Motor Diesel' #Boliana
select

Nome
Jetta Variant            False
Passat                    True
Crossfox                 False
DS5                      False
Aston Martin DB4         False
                         ...
Phantom 2013             False
Cadillac Ciel concept    False
Classe GLK               False
Aston Martin DB5          True
Macan                    False
Name: Motor, Length: 258, dtype: bool

In [9]:
dataset[select] #Selecionando as linhas

                              Motor  ...      Valor
Nome                                 ...
Passat                 Motor Diesel  ...  106161.94
Effa Hafei Picape Baú  Motor Diesel  ...  125684.65
...                             ...  ...        ...
V60                    Motor Diesel  ...  114728.74
Aston Martin DB5       Motor Diesel  ...  122110.90

[26 rows x 6 columns]

In [12]:
#dataset[(dataset.Motor == 'Motor Diesel') & (dataset.Zero_km == True)] #Selecionando com mais de uma condição (E)
dataset[(dataset.Motor == 'Motor Diesel') | (dataset.Zero_km == True)] #Selecionando com mais de uma condição (OU)

                            Motor  ...      Valor
Nome                               ...
Passat               Motor Diesel  ...  106161.94
DS5               Motor 2.4 Turbo  ...  124549.07
...                           ...  ...        ...
XC60              Motor 4.0 Turbo  ...   77675.79
Aston Martin DB5     Motor Diesel  ...  122110.90

[82 rows x 6 columns]

### Utilizando o método query

In [11]:
dataset.query('Motor == "Motor Diesel" and Zero_km == True') #Sintaxe diferente

                            Motor  ...      Valor
Nome                               ...
Sorento              Motor Diesel  ...   81399.35
Cielo Hatch          Motor Diesel  ...  145197.70
Camry                Motor Diesel  ...  138597.27
Aston Martin Virage  Motor Diesel  ...   97290.18
Série 7 Sedã         Motor Diesel  ...   67539.79

[5 rows x 6 columns]

# 5.4 Iterando com DataFrames

In [13]:
for item in dataset: #Colunas
    print(item)

Motor
Ano
Quilometragem
Zero_km
Acessórios
Valor

In [14]:
dataset.iterrows()

In [ ]:
list(dataset.iterrows()) #RETORNA AS LINHAS DO DF COMO LISTA/TUPLA

In [25]:
for index, row in dataset.iterrows():
  if(2019 - row['Ano'] != 0):
    dataset.loc[index, 'Km_media'] = row['Quilometragem'] / (2019 - row['Ano'])
  else:
    dataset.loc[index, 'Km_media'] = 0

dataset

                            Motor   Ano  ...      Valor     Km_media
Nome                                     ...
Jetta Variant     Motor 4.0 Turbo  2003  ...   88078.64  2775.625000
Passat               Motor Diesel  1991  ...  106161.94   204.000000
...                           ...   ...  ...        ...          ...
Aston Martin DB5     Motor Diesel  1996  ...  122110.90   334.130435
Macan             Motor Diesel V6  1992  ...   90381.47  1858.814815

[258 rows x 7 columns]

In [23]:
teste1 = dataset.items()

In [20]:
teste2 = dataset.itertuples()
teste2

# 5.5 Tratamento de dados

In [26]:
dataset.head()

                            Motor   Ano  ...      Valor     Km_media
Nome                                     ...
Jetta Variant     Motor 4.0 Turbo  2003  ...   88078.64  2775.625000
Passat               Motor Diesel  1991  ...  106161.94   204.000000
Crossfox          Motor Diesel V8  1990  ...   72832.16  1280.103448
DS5               Motor 2.4 Turbo  2019  ...  124549.07     0.000000
Aston Martin DB4  Motor 2.4 Turbo  2006  ...   92612.10  1981.307692

[5 rows x 7 columns]

In [27]:
dataset.info() #Informações do DF

<class 'pandas.core.frame.DataFrame'>
Index: 258 entries, Jetta Variant to Macan
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Motor          258 non-null    object
 1   Ano            258 non-null    int64
 2   Quilometragem  197 non-null    float64
 3   Zero_km        258 non-null    bool
 4   Acessórios     258 non-null    object
 5   Valor          258 non-null    float64
 6   Km_media       258 non-null    float64
dtypes: bool(1), float64(3), int64(1), object(2)
memory usage: 24.4+ KB

In [28]:
dataset[dataset.Quilometragem.isna()]

                    Motor   Ano  ...      Valor  Km_media
Nome                             ...
DS5       Motor 2.4 Turbo  2019  ...  124549.07       0.0
A5        Motor 4.0 Turbo  2019  ...   56445.20       0.0
...                   ...   ...  ...        ...       ...
Santa Fe    Motor 3.0 32v  2019  ...  129415.33       0.0
XC60      Motor 4.0 Turbo  2019  ...   77675.79       0.0

[61 rows x 7 columns]

In [29]:
dataset.fillna(0) #Retorna, porém não sobrescreve

                            Motor   Ano  ...      Valor     Km_media
Nome                                     ...
Jetta Variant     Motor 4.0 Turbo  2003  ...   88078.64  2775.625000
Passat               Motor Diesel  1991  ...  106161.94   204.000000
...                           ...   ...  ...        ...          ...
Aston Martin DB5     Motor Diesel  1996  ...  122110.90   334.130435
Macan             Motor Diesel V6  1992  ...   90381.47  1858.814815

[258 rows x 7 columns]

In [30]:
dataset

                            Motor   Ano  ...      Valor     Km_media
Nome                                     ...
Jetta Variant     Motor 4.0 Turbo  2003  ...   88078.64  2775.625000
Passat               Motor Diesel  1991  ...  106161.94   204.000000
...                           ...   ...  ...        ...          ...
Aston Martin DB5     Motor Diesel  1996  ...  122110.90   334.130435
Macan             Motor Diesel V6  1992  ...   90381.47  1858.814815

[258 rows x 7 columns]

In [31]:
dataset.fillna(0, inplace = True) #Retorna e sobrecreve

In [32]:
dataset

                            Motor   Ano  ...      Valor     Km_media
Nome                                     ...
Jetta Variant     Motor 4.0 Turbo  2003  ...   88078.64  2775.625000
Passat               Motor Diesel  1991  ...  106161.94   204.000000
...                           ...   ...  ...        ...          ...
Aston Martin DB5     Motor Diesel  1996  ...  122110.90   334.130435
Macan             Motor Diesel V6  1992  ...   90381.47  1858.814815

[258 rows x 7 columns]

In [33]:
dataset.query('Zero_km == True')

                    Motor   Ano  ...      Valor  Km_media
Nome                             ...
DS5       Motor 2.4 Turbo  2019  ...  124549.07       0.0
A5        Motor 4.0 Turbo  2019  ...   56445.20       0.0
...                   ...   ...  ...        ...       ...
Santa Fe    Motor 3.0 32v  2019  ...  129415.33       0.0
XC60      Motor 4.0 Turbo  2019  ...   77675.79       0.0

[61 rows x 7 columns]

In [34]:
dataset = pd.read_csv('db.csv', sep = ';')

In [35]:
dataset.dropna(subset = ['Quilometragem'], inplace = True) #Retira do DF os registros NA

In [36]:
dataset #197 registros

                 Nome  ...      Valor
0       Jetta Variant  ...   88078.64
1              Passat  ...  106161.94
..                ...  ...        ...
256  Aston Martin DB5  ...  122110.90
257             Macan  ...   90381.47

[197 rows x 7 columns]